####################
## Starship Config ##
####################
# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] 
success_symbol = "[λ](bold #e25e32)"
error_symbol = "[λ](bold red)"

[hostname]
ssh_only = false
format = "[thomaslwk]($style) in "
style = "green"
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncate_to_repo = true
style = "cyan"
home_symbol = "~"

[git_branch]
symbol = ""
truncation_length = 20
style = "purple"

[git_status]
format = '([\[$all_status\]]($style) )'
style = "bold #809fff"
disabled = true
